### PR TITLE
Deleted Indonesial locale from main View

### PR DESCRIPTION
**Pull request by danistep**

### CODE REVIEW

**Comment by bkleinen** [comment]
it would be great to use I18n.available_locales for that, and remove the hidden redundant list of available locales in the view!

**Comment by bkleinen** [comment]
but for a first "little change" absolutely legit!

**Comment by danistep** [comment]
Ok, will do that and push again

**Comment by danistep** [comment]
Is it better?

**Comment by danistep** [comment]
Fixes #61

**Comment by danistep** [comment]
Amended commit message to try out automatic closing of an issue. Please review and merge.

**Comment by bkleinen** [comment]
looks great.

**Pull request merged**
